import 'package:test_drawing/objects/lesson.dart';

List<List<Lesson>> lessonData = [
  //CAPITAL LETTERS
  [
    Lesson(
      character: 'A',
      svgPath: 'assets/images/standard_letters/capital/caps_a.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'B',
      svgPath: 'assets/images/standard_letters/capital/caps_b.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'C',
      svgPath: 'assets/images/standard_letters/capital/caps_c.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'D',
      svgPath: 'assets/images/standard_letters/capital/caps_d.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'E',
      svgPath: 'assets/images/standard_letters/capital/caps_e.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'F',
      svgPath: 'assets/images/standard_letters/capital/caps_f.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'G',
      svgPath: 'assets/images/standard_letters/capital/caps_g.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'H',
      svgPath: 'assets/images/standard_letters/capital/caps_h.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'I',
      svgPath: 'assets/images/standard_letters/capital/caps_i.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'J',
      svgPath: 'assets/images/standard_letters/capital/caps_j.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'K',
      svgPath: 'assets/images/standard_letters/capital/caps_k.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'L',
      svgPath: 'assets/images/standard_letters/capital/caps_l.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'M',
      svgPath: 'assets/images/standard_letters/capital/caps_m.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'N',
      svgPath: 'assets/images/standard_letters/capital/caps_n.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'O',
      svgPath: 'assets/images/standard_letters/capital/caps_o.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'P',
      svgPath: 'assets/images/standard_letters/capital/caps_p.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'Q',
      svgPath: 'assets/images/standard_letters/capital/caps_q.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'R',
      svgPath: 'assets/images/standard_letters/capital/caps_r.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'S',
      svgPath: 'assets/images/standard_letters/capital/caps_s.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'T',
      svgPath: 'assets/images/standard_letters/capital/caps_t.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'U',
      svgPath: 'assets/images/standard_letters/capital/caps_u.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'V',
      svgPath: 'assets/images/standard_letters/capital/caps_v.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'W',
      svgPath: 'assets/images/standard_letters/capital/caps_w.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'X',
      svgPath: 'assets/images/standard_letters/capital/caps_x.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'Y',
      svgPath: 'assets/images/standard_letters/capital/caps_y.svg',
      type: 'standard',
      isCapital: true,
    ),
    Lesson(
      character: 'Z',
      svgPath: 'assets/images/standard_letters/capital/caps_z.svg',
      type: 'standard',
      isCapital: true,
    ),
  ],
  // SMALL LETTERS
  [
    Lesson(
      character: 'a',
      svgPath: 'assets/images/standard_letters/small/small_a.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'b',
      svgPath: 'assets/images/standard_letters/small/small_b.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'c',
      svgPath: 'assets/images/standard_letters/small/small_c.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'd',
      svgPath: 'assets/images/standard_letters/small/small_d.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'e',
      svgPath: 'assets/images/standard_letters/small/small_e.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'f',
      svgPath: 'assets/images/standard_letters/small/small_f.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'g',
      svgPath: 'assets/images/standard_letters/small/small_g.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'h',
      svgPath: 'assets/images/standard_letters/small/small_h.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'i',
      svgPath: 'assets/images/standard_letters/small/small_i.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'j',
      svgPath: 'assets/images/standard_letters/small/small_j.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'k',
      svgPath: 'assets/images/standard_letters/small/small_k.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'l',
      svgPath: 'assets/images/standard_letters/small/small_l.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'm',
      svgPath: 'assets/images/standard_letters/small/small_m.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'n',
      svgPath: 'assets/images/standard_letters/small/small_n.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'o',
      svgPath: 'assets/images/standard_letters/small/small_o.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'p',
      svgPath: 'assets/images/standard_letters/small/small_p.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'q',
      svgPath: 'assets/images/standard_letters/small/small_q.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'r',
      svgPath: 'assets/images/standard_letters/small/small_r.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 's',
      svgPath: 'assets/images/standard_letters/small/small_s.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 't',
      svgPath: 'assets/images/standard_letters/small/small_t.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'u',
      svgPath: 'assets/images/standard_letters/small/small_u.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'v',
      svgPath: 'assets/images/standard_letters/small/small_v.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'w',
      svgPath: 'assets/images/standard_letters/small/small_w.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'x',
      svgPath: 'assets/images/standard_letters/small/small_x.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'y',
      svgPath: 'assets/images/standard_letters/small/small_y.svg',
      type: 'standard',
      isCapital: false,
    ),
    Lesson(
      character: 'z',
      svgPath: 'assets/images/standard_letters/small/small_z.svg',
      type: 'standard',
      isCapital: false,
    ),
  ],

  // WORDS
  [
    Lesson(
      character: 'at',
      svgPath: 'assets/images/words/word_at.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'on',
      svgPath: 'assets/images/words/word_on.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'in',
      svgPath: 'assets/images/words/word_in.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'cat',
      svgPath: 'assets/images/words/word_cat.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'dog',
      svgPath: 'assets/images/words/word_dog.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'pig',
      svgPath: 'assets/images/words/word_pig.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'bike',
      svgPath: 'assets/images/words/word_bike.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'kite',
      svgPath: 'assets/images/words/word_kite.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'apple',
      svgPath: 'assets/images/words/word_apple.svg',
      type: 'word',
      isCapital: true,
    ),
    Lesson(
      character: 'orange',
      svgPath: 'assets/images/words/word_orange.svg',
      type: 'word',
      isCapital: true,
    ),
  ],

  // NUMBERS
  [
    Lesson(
      character: '0',
      svgPath: 'assets/images/numbers/number_0.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '1',
      svgPath: 'assets/images/numbers/number_1.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '2',
      svgPath: 'assets/images/numbers/number_2.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '3',
      svgPath: 'assets/images/numbers/number_3.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '4',
      svgPath: 'assets/images/numbers/number_4.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '5',
      svgPath: 'assets/images/numbers/number_5.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '6',
      svgPath: 'assets/images/numbers/number_6.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '7',
      svgPath: 'assets/images/numbers/number_7.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '8',
      svgPath: 'assets/images/numbers/number_8.svg',
      type: 'number',
      isCapital: true,
    ),
    Lesson(
      character: '9',
      svgPath: 'assets/images/numbers/number_9.svg',
      type: 'number',
      isCapital: true,
    ),
  ],

  //CURSIVE CAPITAL LETTERS
  [
    Lesson(
      character: 'A',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_a.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'B',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_b.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'C',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_c.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'D',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_d.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'E',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_e.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'F',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_f.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'G',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_g.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'H',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_h.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'I',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_i.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'J',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_j.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'L',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_l.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'M',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_m.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'O',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_o.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'P',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_p.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'Q',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_q.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'R',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_r.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'S',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_s.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'T',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_t.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'U',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_u.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'V',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_v.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'W',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_w.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'X',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_x.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'Y',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_y.svg',
      type: 'cursive',
      isCapital: true,
    ),
    Lesson(
      character: 'Z',
      svgPath: 'assets/images/cursive_letters/capital/cursive_caps_z.svg',
      type: 'cursive',
      isCapital: true,
    ),
  ],

  // CURSIVE SMALL LETTERS
  [
    Lesson(
      character: 'a',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_a.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'b',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_b.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'c',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_c.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'd',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_d.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'e',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_e.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'f',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_f.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'g',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_g.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'h',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_h.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'i',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_i.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'j',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_j.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'k',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_k.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'l',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_l.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'm',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_m.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'n',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_n.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'o',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_o.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'p',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_p.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'q',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_q.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'r',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_r.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 's',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_s.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 't',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_t.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'u',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_u.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'v',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_v.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'w',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_w.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'x',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_x.svg',
      type: 'cursive',
      isCapital: false,
    ),
    Lesson(
      character: 'y',
      svgPath: 'assets/images/cursive_letters/small/cursive_small_z.svg',
      type: 'cursive',
      isCapital: false,
    ),
  ]
];
