// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-SRD1gduWRSQxhJX_fc_7nhKFEFg_Kwc',
    appId: '1:627564390619:web:8817783790dbb85e5004fe',
    messagingSenderId: '627564390619',
    projectId: 'handilearn-4cdfa',
    authDomain: 'handilearn-4cdfa.firebaseapp.com',
    storageBucket: 'handilearn-4cdfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwgFtOWgISELDVg5L374Hn1HG2M0HZ4-U',
    appId: '1:627564390619:android:b96bf23f2083f7055004fe',
    messagingSenderId: '627564390619',
    projectId: 'handilearn-4cdfa',
    storageBucket: 'handilearn-4cdfa.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-SRD1gduWRSQxhJX_fc_7nhKFEFg_Kwc',
    appId: '1:627564390619:web:d85e1382b58c4d415004fe',
    messagingSenderId: '627564390619',
    projectId: 'handilearn-4cdfa',
    authDomain: 'handilearn-4cdfa.firebaseapp.com',
    storageBucket: 'handilearn-4cdfa.appspot.com',
  );
}